### ISSUE TITLE
Create a .gitignore file 

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/pieces-os-client-sdk-for-kotlin#17]
To prevent unwanted files from being pushed after contributors make changes, create a .gitignore file. This file should include unwanted files not just for Kotlin but for IDEs as well.

**Comment by jordan-pieces** [comment]
@JeremiahBoothe went ahead and added a .gitignore to this file, anyone who previously was not using a gitignore will need to clear their git cache before attempting to utilize this file.

**Comment by jordan-pieces** [comment]
@kuba-pieces and @JeremiahBoothe both - be sure to update your .gitignore and cached files, just adding as a reminder but closing this issue now
