### ISSUE TITLE
Create a contributor’s guide

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/pieces-os-client-sdk-for-kotlin#18]
A contributor's guide would help new contributors follow a structured guide while contributing, making it easier to maintain the repo.

**Comment by jordan-pieces** [comment]
We can just take the version of the Contributors guide that is on this repo here: https://github.com/pieces-app/pieces-os-client-sdk-for-typescript/blob/main/CONTRIBUTING.md and update it to fit this new location and should not require many additions.
