### ISSUE TITLE
built for too new of a runtime

### ISSUE THREAD

**Issue by kuba-pieces** [pieces-app/pieces-os-client-sdk-for-kotlin#22]
when I try to use the SDK in the lowest supported IJ version (which is also the only fully supported Android Studio) I get:
```
java.lang.UnsupportedClassVersionError: org/piecesapp/client/models/PlatformEnum has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```
We need to downgrade for compatibility reasons. Newer runtimes will support older libraries

**Comment by jordan-pieces** [comment]
ah so we might need to downgrade to 61.0

`java.lang.UnsupportedClassVersionError: org/piecesapp/client/models/PlatformEnum has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

**Comment by jordan-pieces** [comment]
closing this as it has been resolved.
