### ISSUE TITLE
Kuba testing the kotlin sdk on his local machine inside of the intellij plugin environment

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/pieces-os-client-sdk-for-kotlin#3]
We need to test the local functionality of the Kotlin SDK and see if the Gradle build pipeline (that is slightly modified) is functioning properly. There are generated jar files and @kuba-pieces is fairly confident this can be done. 

Once this is completing we can move forward on this deployment 💯 

Steps for your testing: 

- [ ] pull down the repo locally 
- [ ] update reference inside of jetbrains to target the new /directory location 
- [ ] test an endpoints (or) some functionality in pieces intellij plugin to confirm build

**Comment by jordan-pieces** [comment]
apparently the gradle.build is not outputting a is not outputting a jar file, not sure why but need to explore deeper into this pipeline and improving it. reverting back to the old structure and am going to test in a separate repo, will be replaced later if needed.

**Comment by jordan-pieces** [comment]
here is the new PR for this gradle work: 

https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/tree/gradle-build-pipelines

@JeremiahBoothe is going to take a look as well and see what he can uncover. has already been extremely helpful on this `gradle.build` configuration so far!

**Comment by JeremiahBoothe** [comment]
I'm outputting two jar files now.

One version includes, and is limited to, all of the compiled class files from the subfolders under piecesapp > clients.

The second jar file also includes those, plus every other dependency the project relies on.

**Comment by JeremiahBoothe** [comment]
Looking a little bit more into external dependencies and how those are structured, we might be pretty close, I just realized that you could open jar files with 7zip *head explodes*, I'm not sure how to verify atm, but I think only the Manifest needs some work which can be easily done with a text editor and dragged and dropped into the jar.  From analyzing other libraries it looks like there needs to be an export and some class-paths added.

**Comment by jordan-pieces** [comment]
We are good to go on this issue, it has been tested by @JeremiahBoothe locally and is currently expanding on the usage of the API in this kotlin environment!
