### ISSUE TITLE
(3) Publish to Maven Central 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/pieces-os-client-sdk-for-kotlin#4]
Final Step is to publish to maven central and update internal and external docs on the projects availability: 

- [x] publish to maven central 
- [x] update parent repo on [https://github.com/pieces-app/opensource](https://github.com/pieces-app/opensource) with link 
- [x] update readme.md

**Comment by jordan-pieces** [comment]
here is the jira ticket: 

https://issues.sonatype.org/browse/OSSRH-97680?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedId=1300476#comment-1300476

**Comment by jordan-pieces** [comment]
@JeremiahBoothe here is an issue im using to track the final little things

**Comment by jordan-pieces** [comment]
![Screenshot 2023-12-20 at 4 50 11 PM](https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/assets/55861512/f89dcc1f-b125-4141-91ee-5436e5da0a81)

so i would love to respond to this, they did a great job honestly for seeing how the onboarding is across a lot of locations.

**Comment by jordan-pieces** [comment]
![Screenshot 2023-12-20 at 4 51 43 PM](https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/assets/55861512/b45702c5-65ee-4191-bb27-6747a2dec68a)

@JeremiahBoothe heres that message on the steps to take if it doesn't upload automatically.

**Comment by jordan-pieces** [comment]
@JeremiahBoothe will be checking in on this today and will see if the issue is updated 👍

**Comment by JeremiahBoothe** [comment]
Awesome!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordan-pieces** [comment]
DONE: https://central.sonatype.com/artifact/app.pieces.pieces-os-client/pieces-os-client
